name: Luna
version: 0.4
author: MasterDash5
softdepend: [ ProtocolLib ]
main: xyz.dashnetwork.luna.Luna
api-version: 1.13
folia-supported: true

commands:
  build:
    aliases: ["b"]
    permission: "dashnetwork.admin"
  center:
    permission: "dashnetwork.staff"
  nightvision:
    aliases: ["nc", "see", "c"]
    permission: "dashnetwork.staff"
  peek:
    permission: "dashnetwork.staff"

permissions:
  dashnetwork.staff:
    default: op
  dashnetwork.admin:
    default: op
  dashnetwork.owner:
    default: false