name: Luna
version: 0.5
author: MasterDash5
softdepend: [ ProtocolLib ]
main: xyz.dashnetwork.luna.Luna
api-version: 1.13
folia-supported: true

commands:
  build:
  center:
  nightvision:
    aliases: ["nv","see","c"]
  peek:

permissions:
  dashnetwork.staff:
    default: op
  dashnetwork.admin:
    default: op
  dashnetwork.owner:
    default: false